### PR TITLE
optional table refactor & iu support

### PR DESCRIPTION
**Pull request by lastlink**
custom ribbon to use buttons to call this version manager
support for a version text document for users to output which version of the form they've created (not of this integration)

### CODE REVIEW

**Comment by hangie** [comment]
I had another couple of changes I was working on related to this and wanted to check for overlap.
I put a UI ribbon into the interface to allow import/export of various items including everything.  Seems to have a partial overlap with this.

How can we have a conversation on best way forward?

**Comment by lastlink** [comment]
Well I set up the ui ribbon w/ 4 btns. The 1st one loads this extension assuming the 1st vs_loader has already been imported. The next 2 do an export or import excluding data. The last one
"Other Functions" pulls up a dialog that users could add their own custom functions 2 without updating the ui. Using just a message box w/ multiple buttons. The real question is what do we consider to be **core functions** to be called? We can extend the basic ui buttons as much as we like. Just they aren't maintained by this extension & have to be manually imported.

**Comment by acidg** [comment]
Can you update the README please? This needs some more documentation... How can I launch the ribbon?

**Comment by lastlink** [comment]
@acidg you probably need to reimport the VCS_Loader.bas since it was updated in this pull request. Then it should work fine. Launch the ribbon? you need to import the ribbon first.

**Comment by acidg** [comment]
How can I import the ribbon?

**Comment by lastlink** [comment]
Please see the referenced pull request. I made a pull request to update the readme on updating the uiribbon.

**Pull request merged**
