### PR TITLE
Incorporate Hangie's INI capability

### PR DESCRIPTION
**Pull request by hecon5**
Preparing to pull in INI capability; still need to add in a few more tweaks for the INI to be actually called in.

### CODE REVIEW

**Comment by hecon5** [comment]
Because the @hangie branch is so drastically different, will need to create "stepping stones" for backporting their improvements.

**Comment by hangie** [comment]
@hecon5, I have tried a few times to get the changes back without success.  Merging master onto develop and taking that forward is one option.  Attempting to take little pieces will be difficult and will just create more confusion and work to integrate it all.  Some of the big differences were caused by the restructure of some of the code to support exporting different components separately as well as everything.

Also, some of the things that went to master have been replaced by what I did on my develop branch.  Ribbon for one thing.

I also have a new C# addin that goes beyond this and that is where my efforts have been focused.  The drawback is that it is Office 2013+.  I haven't bothered with assessing earlier versions of Office as I had no need, and don't have the versions.

**Comment by hecon5** [comment]
@hangie I use 2013 and beyond, so I'd be interested in trying it out, if you're willing to share. I agree that adding in your changes to the @timabell version would take some doing; this particular one was just to merge in the VCS.cfg features, but upon further inspection, this would likely break several things; ironically before I discovered your fork I'd written a similar feature and then abandoned it because yours also included several other features on top of the config file.

**Comment by hecon5** [comment]
Ready for initial review; for some reason when I added in the INI helper function (strtobool) the file was suddenly marked as "largediff". If someone knows how to sidestep that, I'd be grateful to learn how to not do that...

**Comment by hecon5** [comment]
I'm closing this, it's stale and using the addin, so my ability to update this is reduced.

**Pull request closed without merging**
