### PR TITLE
Merge back the updates previously made

### PR DESCRIPTION
**Pull request by hangie**
Hi,

Sorry for the long absence.  I had been caught up and couldn't check the changes.  I've now merged with the latest master and replaced (mostly alternative) the previous UI implementation with a more complete version that supports all components.
I've also added INI file for configuration.
Fixed a number of bugs (I'll have to go through them later and cross ref them).
Added the XML export of data to fix some bugs.
Export queries as .sql when exporting as SQL and as .bas when not.
Have a look.  Pretty sure this is good to go.

Cheers,
Mark.

### CODE REVIEW

**Comment by hangie** [comment]
This fixes #84, #83, #79, #50, #61

**Comment by hangie** [comment]
Fixes #85, #57.

**Comment by timabell** [comment]
Nice work, thanks for the contribution. I'm afraid I'm going to be a bit picky, it's difficult to see in this PR what has been done as it has many commits and merges. If there are problems it'll be impossible to work out the source of an issue by looking a the history.

Please break this up into one PR per feature / bugfix, and make sure each one is based on timabell/master

Something like:

```
o  timabell/master
  \_ o _ o export-as-sql
  \_ o _ o fix-backslash-escaping
```

**Comment by hangie** [comment]
This will be a bit of a challenge, but I'll do what I can.

**Comment by timabell** [comment]
#88

**Pull request closed without merging**
